### ISSUE TITLE
💡 - Should access key and secret key be optional?

### ISSUE THREAD

**Issue by cep21** [tespkg/actions-cache#24]
**Is your feature request related to a problem? Please describe.**

I use AWS roles and need to turn my ${{ secrets.AWS_ACCESS_KEY }} into the access key the cache action needs using `      uses: aws-actions/configure-aws-credentials`.

This works fine.

```
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets }}
        aws-secret-access-key: ${{  secrets }}
        role-to-assume: arn://cache-role
        role-duration-seconds: 3600
```

Where the action itself has no output and sets environment variables that now exist.  After this, I would like to use the cache action and have it look inside `ENV` for the correct AWS secrets that the above action set.

**Describe the solution you'd like**

Parameters of cache `aws-access-key-id` and `aws-secret-access-key` are optional and cache looks in ENV if they don't exist.  (This is probably the default behavior of the AWS SDK)

**Describe alternatives you've considered**

Embed the tokens directly?:
