### ISSUE TITLE
🐛 - Error in actions should fail step

### ISSUE THREAD

**Issue by whalemare** [tespkg/actions-cache#4]
**Describe the bug**
When step has an error it not crash step.

**To Reproduce**
1. Use and run some incorrect config file
```yml
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  ezcache:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: '0'

      - uses: tespkg/actions-cache@v1
        with:
          endpoint: "127.0.0.1" # optional, default s3.amazonaws.com
          insecure: true # optional, use http instead of https. default false
          accessKey: "1234" # required
          secretKey: "1234" # required
          bucket: mybucket # required
          use-fallback: false # optional, use github actions cache fallback, default true

          # actions/cache compatible properties: https://github.com/actions/cache
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          path: |
            node_modules
            .cache
          restore-keys: |
            ${{ runner.os }}-yarn-
```

After run, workflow is succeed

**Expected behavior**
Workflow failed

**Screenshots**
![Снимок экрана 2021-07-10 в 12 10 58](https://user-images.githubusercontent.com/9128731/125152623-e8eaec80-e177-11eb-9c1e-5039396b10f1.png)
