### ISSUE TITLE
🐛 Restore s3 cache failed with non validating SSL-

### ISSUE THREAD

**Issue by Zheer09** [tespkg/actions-cache#59]
**Describe the bug**
I am using selfhosted minio to upload cache and my case is that i have to send request without validating SSL with port 443 but i get this issue if i choose `insecure: true` with `port: 443`

**Screenshots**

![Image](https://github.com/user-attachments/assets/79138c38-7703-4075-91a0-4ea0892f4538)

**Code/Script reproduction**

```yaml
- name: Build cache
  uses: tespkg/actions-cache@v1
  with:
    endpoint: ${{ env.MINIO_ADDR }}
    insecure: true 
    port: 443
    accessKey: ${{ env.MINIO_ACCESS_KEY }} 
    secretKey: ${{ env.MINIO_SECRET_KEY }} 
    bucket: ${{ env.MINIO_IOS_CACHE_BUCKET }}
    # actions/cache compatible properties: https://github.com/actions/cache
    key: ${{ runner.os }}-xcode-${{ env.FL_XCODE_VERSION }}-build-cache-${{ matrix.environment }}-${{ hashFiles('**/Package.resolved') }}
    path: |
      ${{ env.DERIVED_DATA_PATH }}
      SourcePackages
      ~/Library/Developer/Xcode/DerivedData
```
